# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 https://github.com/Thegegors/til
baseurl:             'til/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Gregory Weiss
  url:               https://google.com
  email:             gregweiss1993@gmail.com  

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
